ALTER TABLE users ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'Zomato';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_working BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_earnings DECIMAL(12, 2) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS today_earnings DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deliveries INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rating DECIMAL(3, 1) DEFAULT 4.5;
ALTER TABLE users ADD COLUMN IF NOT EXISTS risk_score DECIMAL(4, 2) DEFAULT 0.50;
